local_backend: true

backend:
  name: git-gateway
  branch: main   # or master depending on your repo

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
      - { label: "Category", name: "category", widget: "select", options: ["T-Shirts", "Hoodies", "Accessories"] }
      - { label: "In Stock", name: "inStock", widget: "boolean", default: true }
